name: Build

on:
  push: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_RUN_NUMBER: ${{ vars.GITHUB_RUN_NUMBER }}
      GITHUB_ACTION_NUMBER: ${{ vars.GITHUB_RUN_NUMBER }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        uses: gradle/gradle-build-action@v2
      - name: Get Version
        id: var
        run: |
          MESSAGE=$(ls common/build/libs/* | grep sources.jar -v | grep shadow.jar -v | grep slim.jar -v | awk -F 'minequery-common-|.jar' '{print $2}')
          echo "version=$MESSAGE" >> $GITHUB_OUTPUT
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: v${{ steps.var.outputs.version }}
          path: |
            fabric/build/libs
            forge/build/libs
          retention-days: 30