name: Release

on:
  push:
    tags: [ '*' ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      VERSION: ${{ github.ref_name }}
      RELEASE_VERSION: ${{ github.ref_name }}
      SNAPSHOT: ${{ endsWith(github.ref_name, '-snapshot') || contains(github.event.head_commit.message, '[snapshot]') }}
    steps:
      - name: Checkout mod repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 32

      - name: Set up JDK versions
        uses: actions/setup-java@v5
        with:
          java-version: |
            21
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
          validate-wrappers: true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build the mod
        run: ./gradlew --build-cache --info --stacktrace -Pmod_version='${{ env.VERSION }}' assemble

      - name: Publish to CurseForge and Modrinth
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: wxxMbGFI
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          # curseforge-id:
          # curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            fabric/build/libs/*.jar
            neoforge/build/libs/*.jar
          loaders: |
            fabric
            neoforge
          game-versions: |
            [1.21.6,1.22)
          dependencies: |
            fabric-api{modrinth:P7dR8mSH}
            architectury-api{modrinth:lhGA9TYQ}
            midnightlib{modrinth:codAaoxh}
            modmenu(optional)
          java: |
            21
